### ISSUE TITLE
Please clarify documentation for `pandoc-fignos` and `pandoc-eqnos` when a pandoc defaults file is used

### ISSUE THREAD

**Issue by kleinbottle** [tomduck/pandoc-fignos#87]
It took me some time to find out that if I used a pandoc defaults file I needed to specify the _specific choices_ I made so:

```
filters:
  - pandoc-eqnos
  - pandoc-fignos
  - citeproc

metadata:
  xnos-capitalise: true
  xnos-cleveref: true
  eqnos-star-name: Equation
  eqnos-plus-name: equation
  fignos-star-name: Figure
  fignos-plus-name: Figure
```
Thanks.
